#!/usr/bin/env ruby

Vagrant::Config.run do |config|
  config.vm.define :dev do |config|
    config.vm.box         = "precise64"
    config.vm.box_url     = "http://files.vagrantup.com/precise64.box"
    config.vm.host_name   = "dev"

    config.vm.customize ["modifyvm", :id, "--memory", "512"]
    config.vm.customize ["modifyvm", :id, "--cpus", "1"]

    # Shared folders through NFS. This is supported in Mac and Linux. Windows may have
    # issues, see Vagrant site for documentation.
    config.vm.network :hostonly, "10.1.0.3"
    config.vm.share_folder("dev", "/var/www", "../hosts", :nfs => true)
    config.vm.share_folder("dev", "/usr/src/vagrant", "./", :nfs => true)

    config.vm.forward_port 80, 8888 # Apache webserver
    config.vm.forward_port 8000, 8000 # Controller (nginx)
    config.vm.forward_port 22, 2222 # SSH
    config.vm.forward_port 21, 2121 # FTP

    config.vm.provision :shell, :path => "provision/ansible-setup.sh"
    config.vm.provision :shell, :path => "provision/dev-setup.sh"
  end
end
