#!/usr/bin/env ruby

Vagrant::Config.run do |config|
  config.vm.define :dev do |config|
    config.vm.box         = "precise64"
    config.vm.box_url     = "http://files.vagrantup.com/precise64.box"
    config.vm.host_name   = "dev"
    
    # NOTE: You need to comment this out to rebuild successfully.
    config.ssh.private_key_path = "~/.ssh/id_rsa"
    config.ssh.forward_agent = true

    config.vm.customize ["modifyvm", :id, "--memory", "2048"]
    config.vm.customize ["modifyvm", :id, "--cpus", "1"]

    # Shared folders through NFS. This is supported in Mac and Linux. Windows may have
    # issues, see Vagrant site for documentation.
    config.vm.network :hostonly, "10.1.0.3"
    config.vm.share_folder("hosts", "/var/www/hosts", "../hosts", :nfs => true, :create => true)
    config.vm.share_folder("v-root", "/usr/src/vagrant", "./", :nfs => true, :create => true)

    config.vm.forward_port 80, 8888 # varnish
    config.vm.forward_port 8000, 8000 # nginx
    config.vm.forward_port 8080, 8080 # tomcat
    config.vm.forward_port 443, 8443 # SSL
    config.vm.forward_port 22, 2222  # SSH
    config.vm.forward_port 21, 2121  # FTP

    config.vm.provision :shell, :path => "provision/ansible-setup.sh"
    config.vm.provision :shell, :path => "provision/dev-setup.sh"
  end
end
